[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gen-adventure"
version = "0.1.8"
description = "Generate and play AI-powered interactive adventures."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    "requests",
    "google-genai",
    "pygame",
]

authors = [
    {name = "Johnny Matos"}
]

keywords = [
    "ai",
    "game",
    "adventure",
    "pygame",
    "gemini",
    "interactive",
    "story",
    "fantasy"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/DS-Johnny/gen-adventure"

[tool.setuptools.packages.find]
include = ["gen_adventure*"]

[tool.ruff]
line-length = 88